### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by ApteryxNZ** [saifuddin778/mkalgo#1]
This is exactly what I want to use for my experiment. Unfortunately, I am not a Python Person so I need some little assistance. Are you willing to help?

I have a normalised time series of 60,000 1hr points of data from a sensor and I want to match an arbitrary 24hr window (24 points) to the Time Series to ascertain past times when similar activity has occurred.

Sorry for this form of communication, I could not find any other way to contact you.

Kindest Regards

**Comment by saifuddin778** [comment]
Hi,

This algorithm will not directly serve your purpose. What you can do (however) is to find the significant motives out of your bigger time series using this, and then try finding the nearest neighbor from within those motifs against your 24-point smaller set.

Hope this helps.
